<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FluentEventBus.InMemory\FluentEventBus.InMemory.csproj" />
        <ProjectReference Include="..\FluentEventBus.RabbitMq\FluentEventBus.RabbitMq.csproj" />
    </ItemGroup>

</Project>
